### ISSUE TITLE
Tracking Live Points and Simulating Errors

### ISSUE THREAD

**Issue by joshspeagle** [joshspeagle/dynesty#4]
[Skilling (2006)](https://projecteuclid.org/euclid.ba/1340370944) demonstrated that different nested sampling runs can be trivially added together. This property of nested sampling has its roots (I think) in the properties of [Poisson processes](https://www.probabilitycourse.com/chapter11/11_1_3_merging_and_splitting_poisson_processes.php). One of the key insights presented in [Higson et al. (2017)](https://arxiv.org/abs/1703.09701) is that this property also works in reverse, and so it is straightforward to deconstruct a nested sampling run with `K` live points into a series of `K` independent runs with 1 live point (a "strand"). This enables you to probe some of the underlying sampling errors (which are separate from the simulated weights) within a single run using, e.g., bootstrap techniques.

- [x] Add in a way to keep track of each live point (i.e. to preserve each point's unique label) throughout the course of the run.
- [x] Implement a `split` function that takes a run with `K` live points and splits it into `K` strands.
- [x] Implement a `merge` function that takes a set of `N` runs with `K_1, ..., K_N` live points and merges them into 1 run with `K_1 + ... + K_N` live points.
- [x] Implement a `resample` function which splits a run with `K` live points into `K` strands, samples `K` strands *with replacement*, and recombines them into one run.
- [x] Implement an `simulate_error` function which resamples the run and then simulates a corresponding set of weights.
